doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migration'
    # namespace is arbitrary but should be different from App\Migration
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigration
